### ISSUE TITLE
Supporting dark theme

### ISSUE THREAD

**Issue by kmalyshev** [koukibadr/Motion-Toast#105]
Hello, 
First of all, I like your library a lot. However there is one thing that could be a bit improved. Is it possible to add a support for a dark theme? Currently text colors are taken from the user's theme (white if it's dark, black if it's light). However backgrounds are static.

Of course it's possible to define custom toasts but it would be much easier if default toasts supported both themes.

<img width="674" alt="Screenshot 2023-06-29 at 14 33 37" src="https://github.com/koukibadr/Motion-Toast/assets/63050686/2e832fd4-25ff-41e1-90b4-ee129e2e4f11">
<img width="674" alt="Screenshot 2023-06-29 at 14 44 02" src="https://github.com/koukibadr/Motion-Toast/assets/63050686/5df07a57-0bf2-4eaf-b481-9775a6a3463a">

**Comment by koukibadr** [comment]
Thanks @kmalyshev for your support and this feedback
I will work on it

**Comment by koukibadr** [comment]
Light and dark mode support will be available in the next version


<img src="https://github.com/koukibadr/Motion-Toast/assets/36043466/1938cc28-0294-4233-9512-ba263ac42f0b" width="150"/>

<img src="https://github.com/koukibadr/Motion-Toast/assets/36043466/a738c9b2-7dcc-4354-a96d-11fa8b4988c9" width="150"/>

<img src="https://github.com/koukibadr/Motion-Toast/assets/36043466/38552fbf-905f-419f-9e2c-619a3a47ba09" width="150"/>

<img src="https://github.com/koukibadr/Motion-Toast/assets/36043466/aaed9de6-e730-4116-a268-e27b28ec1542" width="150"/>

**Comment by koukibadr** [comment]
@kmalyshev the dark mode changes has been published, if everything is ok please close this issue

**Comment by kmalyshev** [comment]
> @kmalyshev the dark mode changes has been published, if everything is ok please close this issue

I love it! Thanks for such a quick fix.
