### ISSUE TITLE
configuring param:position wont be accepted

### ISSUE THREAD

**Issue by InvokerPhil** [koukibadr/Motion-Toast#112]
<img width="411" alt="image" src="https://github.com/koukibadr/Motion-Toast/assets/125661965/676c86e1-a644-474b-86e7-8532dfd32a2e">

**Comment by koukibadr** [comment]
@InvokerPhil a new version has been published check it out the bug was fixed [https://pub.dev/packages/motion_toast](https://pub.dev/packages/motion_toast)

**Comment by InvokerPhil** [comment]
> @InvokerPhil a new version has been published check it out the bug was fixed https://pub.dev/packages/motion_toast

Thanks for the effort sir!
