### ISSUE TITLE
Black screen on pop

### ISSUE THREAD

**Issue by RawadZogheib** [koukibadr/Motion-Toast#114]
``` dart
MotionToast(
      dismissable: false,
      icon: Icons.error,
      primaryColor: CustomColors.red2,
      secondaryColor: CustomColors.red1,
      toastDuration: const Duration(seconds: 3),
      backgroundType: BackgroundType.solid,
      title: const Text(
        'Error',
        style: TextStyle(fontWeight: FontWeight.bold),
      ),
      description: Text(
        text ?? 'Unexpected Error.',
      ),
      position: MotionToastPosition.bottom,
      animationType: AnimationType.fromRight,
      height: 100,
      width: 350,
    ).show(context); 
```

When I click the back button on any android phone, I got a black screen (If I did it in the moment that my MotionToast timer arrive to his end), Knowing that the PopScope is set to canPop: false, and the dismissable: false. I getting this issue in all my projects!!

**Comment by koukibadr** [comment]
@RawadZogheib I just published a new version 2.8.0, update the motion toast package you have and let me know if the problem persist
