### ISSUE TITLE
Change Opacity

### ISSUE THREAD

**Issue by gumdum** [koukibadr/Motion-Toast#16]
Thank you for this great toast feature! The opacity though is too light for my app. I have a bottom nav bar, and you can't read the text because the opacity is too light.

Can there be a way to set the opacity level?

Thanks again!

**Comment by koukibadr** [comment]
Hello @gumdum thanks for your support , this problem is already fixed in the new version 1.1.0 check it out on the pub.dev 
[https://pub.dev/packages/motion_toast](https://pub.dev/packages/motion_toast)
If the problem persist in your side let me know please

**Comment by gumdum** [comment]
Thanks!
