### ISSUE TITLE
Description text not wrapping?

### ISSUE THREAD

**Issue by gumdum** [koukibadr/Motion-Toast#17]
Is there a way to get the description to wrap? Mine is extending beyond the screen.
![Screen Shot 2021-07-02 at 3 56 34 PM](https://user-images.githubusercontent.com/71924534/124285517-45ce1d80-db4e-11eb-994d-07a9310f5b48.png)

**Comment by gumdum** [comment]
Nevermind. If you use:  \n. it works

**Comment by koukibadr** [comment]
You can also update the description text style
