### ISSUE TITLE
enable click on components when toast is displayed

### ISSUE THREAD

**Issue by koukibadr** [koukibadr/Motion-Toast#31]

**Comment by DigNZ** [comment]
Hi,
I see this is closed but I still have this problem - when the toast is displayed nothing else can be tapped. How do I configure this so that other buttons are still active while the toast is displayed?

**Comment by koukibadr** [comment]
@DigNZ to create a dismissable notification you need to set the position to bottom otherwise if it's on top or center you can't dismiss it when pressing outside the notification
(`notificationPosition = NOTIFICATION_POSITION.bottom`)

**Comment by koukibadr** [comment]
@DigNZ yes you're right i'm working on it already

**Comment by PawelSzymanski89** [comment]
Hello :) how about this bug? :)

**Comment by jagged91** [comment]
I'm also facing this issue - also, it would be nice if the default behavior for toasts was to clear them when tapping.

**Comment by koukibadr** [comment]
the toast is dismissable only when it's showed in the bottom, the dismissable values by default it's false you can set it as true in your call to the toast
I just published a new version with dismissable is set to true by default
[https://pub.dev/packages/motion_toast](https://pub.dev/packages/motion_toast)
for now when showing the toast on top or center there's no dismissable behavior support in the package but I'm working on it

thanks for your support !!

**Comment by koukibadr** [comment]
@jagged91 @PawelSzymanski89 @DigNZ I just published a new  version, this time you can dismiss the toast when it's displayed on top or center also
check this new version 
[https://pub.dev/packages/motion_toast](https://pub.dev/packages/motion_toast)

**Comment by jobic10** [comment]
> @jagged91 @PawelSzymanski89 @DigNZ I just published a new version, this time you can dismiss the toast when it's displayed on top or center also check this new version https://pub.dev/packages/motion_toast

Yeah, the new version solves this. 
I think it's safe to close this Issue. 
Thanks @koukibadr for the package.
