### ISSUE TITLE
Two toast nearly the same time sticks

### ISSUE THREAD

**Issue by bksubhuti** [koukibadr/Motion-Toast#32]
I have an app that asks for flutterbackground
 permission and displays and error and success in quick succession for certain case.
the success (actually custom).. sticks.. you need to "flick" it to turn it off.

Love your toasts.. a toast to you.
I'm a monk.. cannot give coffee. but share merit with you for a free dist app:)..

Bug is minor.. I'm still rolling out with your package.  I hope I can re-arrange the logic.

**Comment by koukibadr** [comment]
Thanks for letting me know about your feedback about the package really appreciate it thanks
For the bug I will check it with an example find a solution and i will let you know about the new version.

**Comment by koukibadr** [comment]
Hello @bksubhuti this bug is fixed it will be available in the version 1.0.4

**Comment by bksubhuti** [comment]
Excellent! Beautiful package.  I will be releasing my app "Buddhist Sun" with your toast "as is" ...because it is sooo 
 good.  as soon as they approve.  That is a other story.

**Comment by koukibadr** [comment]
Awesome @bksubhuti I wish you all the success in this app!
