### ISSUE TITLE
background color of container.

### ISSUE THREAD

**Issue by RazaShabbir-vrc** [koukibadr/Motion-Toast#45]
Hey, I just noticed when the toast appears it just comes up with this white background artifact which I tried to wrap around with color however, it doesn't change the white background that you see. Should just show me the original background that I have with scaffold but maybe the listview behind it is interfering with the toast itself. Do you see any workaround to this? Attaching the SS for reference.
![image](https://user-images.githubusercontent.com/85259282/143930319-a9327f53-81b0-435d-b3e0-344e4418ae5a.png)

**Comment by koukibadr** [comment]
@RazaShabbir-vrc yes there's a white background added to the toast itself because the toast is adding little opacity to the main color in the content (for example the green in the SS)
there's no workaround for the moment but we can add an attribute to enable or disable the white background in the next version

**Comment by koukibadr** [comment]
@RazaShabbir-vrc now you can change background style by choosing one of this options
`enum BACKGROUND_TYPE { transparent, solid, lighter }`
and also you can define a secondary color that will be applied to the sidebar and the icon 
```dart
MotionToast(
      icon: Icons.zoom_out,
      primaryColor: Colors.grey[700]!,
      secondaryColor: Colors.yellow,
      backgroundType: BACKGROUND_TYPE.transparent,
      title: 'Two Color Motion Toast',
      titleStyle: TextStyle(
        fontWeight: FontWeight.bold,
        color: Colors.yellow,
      ),
      description: 'Another motion toast example',
      descriptionStyle: TextStyle(
        color: Colors.yellow,
      ),
      position: MOTION_TOAST_POSITION.center,
      height: 100,
    ).show(context);
```
this will give you : 
<img  src="https://user-images.githubusercontent.com/36043466/144618933-086bef78-9ad8-48f4-baec-7d1105595c0f.png" height="150"/>
