### ISSUE TITLE
Display second toast in same time error

### ISSUE THREAD

**Issue by PawelSzymanski89** [koukibadr/Motion-Toast#54]
When i'll show two toast's in same time - first do not hide - is always visible and screen is not clickabe

**Comment by koukibadr** [comment]
Thanks for your feedback and issue report @PawelSzymanski89

**Comment by PawelSzymanski89** [comment]
@koukibadr  any predictions about fix?

**Comment by koukibadr** [comment]
@PawelSzymanski89 I'm working on the issue

**Comment by koukibadr** [comment]
@PawelSzymanski89 the issue is fixed in the new version 2.1.1
[https://pub.dev/packages/motion_toast](https://pub.dev/packages/motion_toast)

if the bug is fixed on your side you can close this issue.
Thanks for contributing to the project

**Comment by PawelSzymanski89** [comment]
@koukibadr thanks! your lib is awesome :)
