### ISSUE TITLE
Widget parameters

### ISSUE THREAD

**Issue by Kadnium** [koukibadr/Motion-Toast#58]
Hello, nice package. One thing that would make the developing experience better is to show the default parameters in the widget constructor. Here is how vs code displays it currently, for example I don't know what is the value of defaultAnimationType or toastDuration and I have to go check your package code. Usually flutter widgets give the actual values in constructor so they will be visible to outside.
![image](https://user-images.githubusercontent.com/32646472/157715584-65216f27-e698-4a30-82cb-e4bd384183f1.png)

Example photo of Column's constructor
![image](https://user-images.githubusercontent.com/32646472/157717012-1a14dd3d-69df-4f54-ae5b-3543eb5cde5b.png)

**Comment by koukibadr** [comment]
Thanks for the feedback @Kadnium changes are now available in the new version 2.1.4 [https://pub.dev/packages/motion_toast](https://pub.dev/packages/motion_toast)

**Comment by koukibadr** [comment]
Feel free to close this issue, can't wait to get other feedback and ideas from you !
