### ISSUE TITLE
Not `dismissable`

### ISSUE THREAD

**Issue by jobic10** [koukibadr/Motion-Toast#59]
```
    MotionToast.error(
      title: Text('Error'),
      animationType: ANIMATION.fromRight,
      position: MOTION_TOAST_POSITION.top,
      description: Text('desc'),
    ).show(context);
  
```

With the above code, I have to wait till the toast leaves before the app resumes.
If I didn't use `MOTION_TOAST_POSITION.top`, it works well.
So, it does not dismiss (on click) when `position` is set to `top`.

More so, if you remove `animationType` from the above code snippet, it doesn't show the toast
Thanks

**Comment by jobic10** [comment]
I've seen the reason for not showing the toast, it is the assertion:
```
   assert(
      (position == MOTION_TOAST_POSITION.bottom &&
              animationType != ANIMATION.fromTop) ||
          (position == MOTION_TOAST_POSITION.top &&
              animationType != ANIMATION.fromBottom) ||
          (position == MOTION_TOAST_POSITION.center),
    );
```

**Comment by koukibadr** [comment]
@jobic10 thanks for your feedback and your contribution I will publish a new version ASAP

**Comment by jobic10** [comment]
Thanks @koukibadr

**Comment by koukibadr** [comment]
Hello again @jobic10 I just published a new version of the package check it out 
[https://pub.dev/packages/motion_toast](https://pub.dev/packages/motion_toast)

**Comment by jobic10** [comment]
It's cool ☺ 
Thanks for this 🚀
