### ISSUE TITLE
App popping out if Toast not dismissed manually

### ISSUE THREAD

**Issue by OutdatedGuy** [koukibadr/Motion-Toast#61]
My Navigator stack have 2 pages
1. OTP Page (At top of stack)
2. Login Page (Below OTP Page)

When I display `Motion Toast` on OTP Page and don't dismiss it manually, it is popping everything

Am I missing something?

My MotionToast code snippet:
```dart
MotionToast.error(
  description: Text(e.toString().split(': ')[1]),
  dismissable: true,
).show(context);
```

Here's the video for that:

https://user-images.githubusercontent.com/74326345/162615390-3d14cb7f-c856-4eed-a5f6-fecbe722267c.mp4

**Comment by koukibadr** [comment]
Thanks for your contribution I will publish a new version of the package by the end of the day (20h GMT)
I will let you know once the new version is published

**Comment by OutdatedGuy** [comment]
@koukibadr why is this issue reopened?

**Comment by koukibadr** [comment]
No I think it's a just a wrong action it's closed
