### ISSUE TITLE
long text gets render flow error

### ISSUE THREAD

**Issue by suhail600** [koukibadr/Motion-Toast#66]
long texts gets render flow error when , 

  layoutOrientation: ToastOrientation.rtl, 
is used

**Comment by koukibadr** [comment]
Thanks for your feedback @suhail600 I will fix it ASAP

**Comment by koukibadr** [comment]
Hello again @suhail600 I just fixed the bug it will be available in the next version

![Screenshot_1656192614](https://user-images.githubusercontent.com/36043466/175791137-f0f7a7df-7dcb-4dc1-b699-8804138ef2a5.png)

**Comment by koukibadr** [comment]
Hello @suhail600 I fixed this issue you can check it out
[https://pub.dev/packages/motion_toast](https://pub.dev/packages/motion_toast)

**Comment by abdalazeez1** [comment]
same error  when using long title 

 motion_toast: ^2.2.1
this my custome widget i try to put Flexible but isn't work 

showToastS(
        {required BuildContext context,
        required String text,
        required String description}) =>
    MotionToast.success(
      title: Flexible(child: Text(text,overflow: TextOverflow.ellipsis,)),
      description: Flexible(child: Text(description,overflow: TextOverflow.ellipsis)),
    ).show(context);


![Screenshot_20220707-214935](https://user-images.githubusercontent.com/66934042/177850293-d8c30703-6933-4ceb-8fcb-484306a33691.jpg)

**Comment by koukibadr** [comment]
Sorry for the late response @abdalazeez1 
The only solution for now is to set a custom height to the toast you are showing

**Comment by abdalazeez1** [comment]
When i add text over flow isn't work because you dont add expanded inside column 
If i found free time i will upload pull request thanks for time

**Comment by koukibadr** [comment]
Okay thanks for your contribution

**Comment by abdalazeez1** [comment]
@koukibadr 
this simple example shoy you how to make toast responsive  you can't add singleChildScrollView its not solve problem

`showToast({
  required BuildContext context,
  required String text,
  required String description,
  required ContentType contentType,
}) {
  final  snackBar = SnackBar(
      elevation: 3,
      behavior: SnackBarBehavior.floating,
      backgroundColor: Colors.transparent,
      padding: REdgeInsets.symmetric(vertical: 24, horizontal: 8),
      content: ClipRRect(
        borderRadius: PBorderRadius.borderRadiusAllM1,
        child: BackdropFilter(
          filter: ImageFilter.blur(sigmaX: 5, sigmaY: 5),
          child: Container(
            padding: REdgeInsets.all(8),
            color: Colors.green.withOpacity(.7),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Flexible(
                  child: Text(
                    text,
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                    style: Theme.of(context)
                        .textTheme
                        .titleSmall
                        ?.copyWith(color: Colors.white),
                  ),
                ),
                Flexible(
                    child: Text(
                  description,
                  maxLines: 3,
                  overflow: TextOverflow.ellipsis,
                  style: Theme.of(context)
                      .textTheme
                      .bodySmall
                      ?.copyWith(color: Colors.white),
                ))
              ],
            ),
          ),
        ),
      ));

  ScaffoldMessenger.of(context).showSnackBar(snackBar);
}`

**Comment by koukibadr** [comment]
@abdalazeez1 can you please use the latest version I published yesterday to see if the problem persist
