### ISSUE TITLE
Error With Material3

### ISSUE THREAD

**Issue by RawadZogheib** [koukibadr/Motion-Toast#97]
When I set useMaterial3 = true in the main this happen to the motion_toast.

<img width="1425" alt="Screenshot 2023-02-08 at 14 52 25" src="https://user-images.githubusercontent.com/89975932/217535161-ef48d711-179e-4f43-b57c-00739cc14ebc.png">

**Comment by koukibadr** [comment]
thanks @RawadZogheib for filling this issue 
once a new version is pulished I will let you know

**Comment by koukibadr** [comment]
Hello @RawadZogheib a new version is published fixing the material3 error 
[https://pub.dev/packages/motion_toast](https://pub.dev/packages/motion_toast)

**Comment by RawadZogheib** [comment]
Yes it works correctly now, thank you !!
